
builds:

- id: prudence
  main: ./prudence
  binary: prudence
  goarch:
  - amd64
  - wasm
  goos:
  - linux
  - darwin
  - windows
  - js
  ldflags:
  - -X 'github.com/tliron/kutil/version.GitVersion={{.Env.VERSION}}'
  - -X 'github.com/tliron/kutil/version.GitRevision={{.Env.REVISION}}'
  - -X 'github.com/tliron/kutil/version.Timestamp={{.Env.TIMESTAMP}}'

- id: xprudence
  main: ./xprudence
  binary: xprudence
  goarch:
  - amd64
  - wasm
  goos:
  - linux
  - darwin
  - windows
  - js
  ldflags:
  - -X 'github.com/tliron/kutil/version.GitVersion={{.Env.VERSION}}'
  - -X 'github.com/tliron/kutil/version.GitRevision={{.Env.REVISION}}'
  - -X 'github.com/tliron/kutil/version.Timestamp={{.Env.TIMESTAMP}}'

nfpms:

- formats:
  - rpm
  - deb
  homepage: https://github.com/tliron/prudence
  maintainer: Tal Liron <tal.liron@gmail.com>
  description: A lightweight web framework built for scale.
  license: Apache 2.0

archives:

- files:
  - README.md
  - LICENSE
  - NOTICE

  format_overrides:
  - goos: windows
    format: zip

checksum:

  name_template: checksums.txt

release:

  #disable: true
  #prerelease: true

  github:
    owner: tliron
    name: prudence
