#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

"$HERE/build"
"$GOPATH/bin/prudence" run "$ROOT/examples/js/prudence.js" -vv

#cd "$ROOT"
#go run main.go
