#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

"$HERE/build"

xprudence build -v \
    --directory="$ROOT/examples/plugin" \
    --local="$ROOT"

#    --replace=github.com/tliron/kutil=/Depot/Projects/RedHat/kutil

prudence run "$ROOT/examples/plugin/start.js" -vv
