#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

"$HERE/build"

xprudence build -v \
    --plugin=github.com/tliron/prudence/examples/plugin \
    --replace=github.com/tliron/prudence=/Depot/Projects/Three\ Crickets/prudence-go \
    --replace=github.com/tliron/kutil=/Depot/Projects/RedHat/kutil

prudence run "$ROOT/examples/plugin/start.js" -vv
