#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

function c () {
    if [ "$PROTOCOL" == https ]; then
        curl --silent --insecure "https://$1" "${@:2}"
    else
        curl --silent "http://$1" "${@:2}"
    fi
}

c localhost:8080/person/Tal/chores \
    --request PUT \
    --data '["cleaning", "shopping", "cooking"]'

c localhost:8080/person/Tal/chores?scope=all \
    --header 'Accept: text/html' \
    --header 'Accept-Encoding: br' | brotli --decompress

c localhost:8080/person/Tal/chores?scope=all \
    --header 'Accept: text/html' \
    --header 'Accept-Encoding: gzip' | gunzip

c localhost:8080/person/Tal/chores?scope=all \
    --header 'Accept: text/html' \
    --header 'Accept-Encoding: deflate' | openssl zlib -d

# https://stackoverflow.com/questions/3178566/how-to-deflate-with-a-command-line-tool-to-extract-a-git-object
