#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

curl localhost:8080/person/Tal/chores \
    --silent \
    --request PUT \
    --data '["cleaning", "shopping", "cooking"]'

curl localhost:8080/person/Tal/chores?scope=all \
    --silent \
    --header 'Accept: text/html' \
    --header 'Accept-Encoding: br' | brotli --decompress

curl localhost:8080/person/Tal/chores?scope=all \
    --silent \
    --header 'Accept: text/html' \
    --header 'Accept-Encoding: gzip' | gunzip

curl localhost:8080/person/Tal/chores?scope=all \
    --silent \
    --header 'Accept: text/html' \
    --header 'Accept-Encoding: deflate' | openssl zlib -d

# https://stackoverflow.com/questions/3178566/how-to-deflate-with-a-command-line-tool-to-extract-a-git-object
